// Build script: embed the entire `src/templates` tree into the binary.
//
// Instead of hand-maintaining a list of `include_str!` constants in
// `template.rs`, we walk `src/templates` at compile time and generate a single
// `EMBEDDED_TEMPLATES: &[(&str, &str)]` table of (relative_path, file_contents).
// Adding, moving, or renaming a template file therefore requires **no** Rust
// changes — the file is picked up automatically on the next build.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Read CARGO_MANIFEST_DIR at runtime (not via env!, which is baked in when
    // the build script binary is compiled) so a stale build-script binary from
    // before a project directory rename does not point at a dead path.
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let templates_dir = manifest_dir.join("src").join("templates");

    // Re-run if the templates directory itself changes (files added/removed).
    println!("cargo:rerun-if-changed={}", templates_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Collect (relative_path, absolute_path) for every file, sorted by relative
    // path so output is deterministic and stable across builds/platforms.
    let mut files: BTreeMap<String, PathBuf> = BTreeMap::new();
    collect_files(&templates_dir, &templates_dir, &mut files);

    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs — do not edit.\n\
         /// Every file under `src/templates`, embedded at compile time as\n\
         /// `(relative_path, file_contents)` pairs. Sorted by relative path.\n\
         pub static EMBEDDED_TEMPLATES: &[(&str, &str)] = &[\n",
    );

    for (rel, abs) in &files {
        // Emit a `cargo:rerun-if-changed` for each file so edits trigger rebuild.
        println!("cargo:rerun-if-changed={}", abs.display());

        // Use string literals for the relative path (always simple) and
        // `include_str!` with an absolute path for the content so we never copy
        // file bytes through the build script (keeps it cheap and exact).
        writeln!(
            generated,
            "    ({:?}, include_str!({:?})),",
            rel,
            abs.display().to_string()
        )
        .unwrap();
    }

    generated.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest = out_dir.join("embedded_templates.rs");
    fs::write(&dest, generated).expect("failed to write embedded_templates.rs");
}

/// Recursively collect every file under `dir`, keyed by its path relative to
/// `root` (using forward slashes for cross-platform stability).
fn collect_files(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
        } else if path.is_file() {
            if let Ok(rel) = path.strip_prefix(root) {
                let rel = rel
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy())
                    .collect::<Vec<_>>()
                    .join("/");
                out.insert(rel, path.clone());
            }
        }
    }
}
